[package]
name = "wx_func"
version = "0.1.0"
authors = ["johny.li <johny.li@selmit.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bytes = { version = "1.0", features = ["serde"] }
url = "2.2"
reqwest = { version = "0.11", features = ["blocking", "json", "multipart"] }
tokio = { version = "1.0", features = ["full"] }
# quick-xml = { version = "0.20", features = [ "serialize" ] }
serde = { version = "1.0", features = [ "derive" ] }
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0"
dotenv = "0.15"
# tonic = "0.4"
# prost = "0.7"
futures = "0.3"
async-trait = "0.1"
roxmltree = { version = "0.14", features = [ "std" ] }
xmlwriter = "0.1"
# exile = "0.0.7"
sha-1 = "0.9"
block-modes = "0.8.1"
aes = "0.7.4"
hex-literal = "0.3.3"
base64ct = "1.0.0"

[build-dependencies]
# tonic-build = "0.4"
tokio-test = "0.4"
